vim.opt.shiftwidth = 4
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.wildmode = "longest:full"
vim.opt.signcolumn = "yes"
vim.opt.undofile = true
vim.opt.breakindent = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.timeout = true
vim.opt.timeoutlen = 10000
vim.opt.updatetime = 250
vim.opt.list = true
vim.opt.listchars = {
  eol = ' ', -- if you want some option: ↲, ↵,
  multispace = '␣',
  lead = '·',
  leadmultispace = '··',
  tab = '  ⇥',
  leadtab = '>>',
  trail = '␣',
  nbsp = '␣',
  precedes = '<',
  extends = '>',
  conceal = '#',
}
vim.opt.inccommand = 'split'
vim.opt.cursorline = false
vim.opt.scrolloff = 10
vim.opt.confirm = false
vim.o.splitright = true
vim.o.splitbelow = true
